#!/bin/bash

# Purpose:Daily System Check
# Date:6/29/2026
# Usage:Script Practice

echo "==========================="
echo " SYSTEM REPORT "
echo "==========================="

echo "--- HOSTNAME ---"
hostname


echo ""
echo "--- DATE ---"
echo "$(date)"


echo ""
echo "--- DISK USAGE ---"
df -h /


echo ""
echo "--- MEMORY ---"
free -h


echo ""
echo "==========================="
echo "  END OF REPORT"
echo "==========================="

DISK=$(df / | awk 'NR==2 {print $5}' | tr -d '%')


# if/else that warns if disk is above 80%
if [ "$DISK" -gt 80 ]; then
   echo "WARNING: Disk usages is at ${DISK}% - Take action!"
else
   echo "Disk usage is at ${DISK}% - Good!"
fi
